# Generated by Django 2.0.3 on 2018-03-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateField(blank=True, null=True, verbose_name='Ocurred At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('latitude', models.CharField(max_length=40, verbose_name='Latitude')),
                ('longitude', models.CharField(max_length=40, verbose_name='Longitude')),
                ('is_open_data', models.BooleanField(default=False, verbose_name='Is Open Data')),
                ('is_twitter', models.BooleanField(default=False, verbose_name='Is Twitter')),
            ],
            options={
                'verbose_name': 'Accident',
                'verbose_name_plural': 'Accidents',
                'ordering': ['occurred_at'],
            },
        ),
    ]
