# Generated by Django 2.0.3 on 2018-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='text',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Text'),
        ),
    ]
