# Generated by Django 2.0.3 on 2018-03-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accident',
        ),
    ]
